services:
  mongo:
    restart: unless-stopped

  backend:
    environment:
      JWT_SECRET: jb993ENmSNHXNHGOBr9N2hGt+1JxSMWn4JivGlHi5vSHChLbAI84mwBcERgzhrKl
      CORS_ALLOWED_ORIGINS: http://methuselah.local:3001
      SLACK_ERROR_TOKEN: ${SLACK_ERROR_TOKEN:-}
    restart: unless-stopped

  frontend:
    ports:
      - "3001:80"
    restart: unless-stopped
